CC = gcc
CFLAGS ?= -O2 -g
 
CFLAGS += -m32
 
CFLAGS += -std=gnu99
 
CFLAGS += -Wall -Werror -Wformat-security -Wignored-qualifiers -Winit-self \
	-Wswitch-default -Wpointer-arith -Wtype-limits -Wempty-body \
	-Wstrict-prototypes -Wold-style-declaration -Wold-style-definition \
	-Wmissing-parameter-type -Wmissing-field-initializers -Wnested-externs \
	-Wstack-usage=4096 -Wmissing-prototypes -Wfloat-equal -Wabsolute-value
 
CFLAGS += -fsanitize=undefined -fsanitize-undefined-trap-on-error
 
.DELETE_ON_ERROR:
 
.PHONY: all
all: integral
 
integral: functions.o integral.c integral.h
	$(CC) $(CFLAGS) -o $@ $^
 
functions.o: functions.asm
	nasm -f elf32 -o $@ $<
 
.PHONY: clean
clean:
	rm -rf *.o
 
.PHONY: test
 
test: integral
	./integral --test-root 1:2:1.0:2.0:0.0001:1.1605796289806
	./integral --test-root 1:3:-1.5:0.5:0.1:-0.5850107647134
	./integral --test-root 2:3:-4.0:-2.0:0.03:-3.3150082875207
	./integral --test-integral 1:-5.12:4.01:0.001:26.766233835
	./integral --test-integral 2:0.123:11.001:0.012:1035.501654591809
	./integral --test-integral 3:0.12:0.55:0.00001:-0.5818186666666667
